// <auto-generated />
using ContactManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250310143820_initalcontactmanagment")]
    partial class initalcontactmanagment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactManagementAPI.Data.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ContactManagementAPI.Data.Entities.Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Funds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "investorflow X Credit Fund"
                        },
                        new
                        {
                            Id = 2,
                            Name = "London 1X Credit Fund"
                        },
                        new
                        {
                            Id = 3,
                            Name = "London 2X Credit Fund"
                        },
                        new
                        {
                            Id = 4,
                            Name = "London 3X Credit Fund"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ABC Hedge Fund"
                        },
                        new
                        {
                            Id = 6,
                            Name = "BAC Hedge Fund"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Google Startup Fund"
                        },
                        new
                        {
                            Id = 8,
                            Name = "IBM Startup Fund"
                        },
                        new
                        {
                            Id = 9,
                            Name = "London XX Investment Fund"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bristol XX Investment Fund"
                        });
                });

            modelBuilder.Entity("ContactManagementAPI.Data.Entities.FundContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<int>("FundId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("FundId");

                    b.ToTable("FundContacts");
                });

            modelBuilder.Entity("ContactManagementAPI.Data.Entities.FundContact", b =>
                {
                    b.HasOne("ContactManagementAPI.Data.Entities.Contact", "Contact")
                        .WithMany("FundContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactManagementAPI.Data.Entities.Fund", "Fund")
                        .WithMany("FundContacts")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ContactManagementAPI.Data.Entities.Contact", b =>
                {
                    b.Navigation("FundContacts");
                });

            modelBuilder.Entity("ContactManagementAPI.Data.Entities.Fund", b =>
                {
                    b.Navigation("FundContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
